DEBUG 2022-07-20 15:49:42.788 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-07-20 15:49:42.788 UTC: 	 Running on: Linux lxplus748.cern.ch 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-07-20 15:49:42.788 UTC: 	 Executing command: 'submit'
DEBUG 2022-07-20 15:49:42.789 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sungwon/.crab3
INFO 2022-07-20 15:49:42.789 UTC: 	 Will use CRAB configuration file crabConfig_L3FromL1TkMuon_D88Geo_TTTo2L2Nu_ntupler.py
DEBUG 2022-07-20 15:49:42.789 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-07-20 15:49:42.790 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-07-20 15:49:42.790 UTC: 	 Working area '/afs/cern.ch/user/s/sungwon/private/MuonHLT_ML/Multi_CMSSW_12_2nd/CMSSW_12_4_0/src/MuonHLTTool/MuonHLTNtupler/test/test_geo_D88/crab_PhaseII_CMSSW_12_4_0_20220721/crab_PU200-TTTo2L2Nu_L3FromL1TkMuon_20220721' already exists 
Please change the requestName in the config file
ERROR 2022-07-20 15:49:42.790 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/s/sungwon/private/MuonHLT_ML/Multi_CMSSW_12_2nd/CMSSW_12_4_0/src/MuonHLTTool/MuonHLTNtupler/test/test_geo_D88/crab_PhaseII_CMSSW_12_4_0_20220721/crab_PU200-TTTo2L2Nu_L3FromL1TkMuon_20220721' already exists 
Please change the requestName in the config file
INFO 2022-07-20 15:49:42.793 UTC: 	 Log file is /afs/cern.ch/user/s/sungwon/private/MuonHLT_ML/Multi_CMSSW_12_2nd/CMSSW_12_4_0/src/MuonHLTTool/MuonHLTNtupler/test/test_geo_D88/crab.log
